import { expect, test } from "@playwright/test";

test.setTimeout(10_000);

test("行情单击预览、双击进入个股，F10 与返回保持选择和图表周期", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  await expect(page.locator('.desktop-terminal[data-view="quotes"]')).toBeVisible();
  const row = page.locator('.ag-row[row-id="002156"]');
  await row.click();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await expect(page.locator('.desktop-terminal[data-view="quotes"]')).toBeVisible();
  await row.dblclick();
  await expect(page.locator('.desktop-terminal[data-view="stock"]')).toBeVisible();
  await expect(page.getByRole("navigation", { name: "个股列表" })).toBeVisible();
  await page.locator("#section-trade").getByRole("button", { name: "日K", exact: true }).click();
  await page.locator("#section-trade").getByRole("button", { name: "无", exact: true }).click();
  await page.getByRole("button", { name: "公司资料 F10", exact: true }).click();
  await expect(page.locator("#section-company")).toBeVisible();
  await expect(page.locator("#section-trade")).toBeHidden();
  await page.getByRole("button", { name: "走势图", exact: true }).click();
  await expect(page.locator(".chart-tab.active")).toHaveText("日K");
  await expect(page.locator("#section-trade").getByRole("button", { name: "无", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "返回行情", exact: true }).click();
  await expect(page.locator('.desktop-terminal[data-view="quotes"]')).toBeVisible();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await expect(page.getByRole("contentinfo", { name: "模拟账户摘要" })).toBeInViewport();
});

test("交易和游戏管理各有入口，切换不丢委托草稿，横竖屏使用不同导航", async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  const quantity = page.getByPlaceholder("买入按手；零股一次卖完");
  await quantity.fill("300");
  await nav.getByRole("button", { name: "游戏", exact: true }).click();
  await expect(page.getByRole("button", { name: "保存当前进度" })).toBeVisible();
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  await expect(quantity).toHaveValue("300");
  await expect(page.locator("#section-positions")).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("navigation", { name: "主导航" })).toBeVisible();
  await expect(nav).toHaveCount(0);
  await expect(page.locator(".desktop-account-bar")).toHaveCount(0);
});

test("当前个股交易入口纠正另一证券草稿，F10 与公司页始终跟随个股", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  const code = page.locator('#section-order').getByLabel('股票', {exact:true});
  await code.selectOption("002156");
  await page.getByPlaceholder("买入按手；零股一次卖完").fill("300");
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "交易此股票", exact: true }).click();
  await expect(code).toHaveValue("600101");
  await expect(page.getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("300");
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await page.keyboard.press("F10");
  await expect(page.getByRole("region", {name:"公司信息"})).toHaveAttribute("data-company-id", "C-600101");
  await page.getByRole("navigation", {name:"个股列表"}).getByRole("button", {name:/芯片科技/}).click();
  await expect(page.getByRole("region", {name:"公司信息"})).toHaveAttribute("data-company-id", "C-002156");
});

test("1020窗口个股图保留完整时间轴，价量左右边界一致且盘口不溢出", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  const chart = page.locator(".desktop-intraday");
  await expect(chart).toBeVisible();
  await expect(chart.getByText("11:30/13:00", { exact: true })).toBeVisible();
  const price = await page.locator(".intraday-price-plot").boundingBox();
  const volume = await page.locator(".intraday-volume-plot").boundingBox();
  expect(price).not.toBeNull();
  expect(volume).not.toBeNull();
  expect(Math.abs(price!.x - volume!.x)).toBeLessThan(1);
  expect(Math.abs(price!.width - volume!.width)).toBeLessThan(1);
  expect(price!.width).toBeGreaterThan(380);
  await expect(page.locator(".order-book")).toBeInViewport();
  await expect(page.getByRole("contentinfo", { name: "模拟账户摘要" })).toBeInViewport();
  const overflow = await page.locator(".terminal-body").evaluate(el => el.scrollWidth > el.clientWidth);
  expect(overflow).toBe(false);
  await page.locator("#section-trade").getByRole("button", { name: "日K", exact: true }).click();
  await expect(chart).toHaveCount(0);
  await page.locator("#section-trade").getByRole("button", { name: "分时", exact: true }).click();
  await expect(chart).toBeVisible();
});

test("均线按钮可多选，关闭其中一条不影响其他均线", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "日K", exact: true }).click();
  const group = page.getByRole("group", { name: "均线（可多选）" });
  const ma20 = group.getByRole("button", { name: /^MA20：/ });
  const ma60 = group.getByRole("button", { name: /^MA60：/ });
  await expect(group.getByRole("button")).toHaveCount(5);
  await expect(ma20).toHaveAttribute("aria-pressed", "true");
  await expect(ma60).toHaveAttribute("aria-pressed", "true");
  await ma20.click();
  await expect(ma20).toHaveAttribute("aria-pressed", "false");
  await expect(ma60).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "分时", exact: true }).click();
  await page.getByRole("button", { name: "日K", exact: true }).click();
  await expect(ma60).toHaveAttribute("aria-pressed", "true");
  await expect(ma20).toHaveAttribute("aria-pressed", "false");
});

test("共用K线支持滚轮、Shift平移、点击对齐和双指缩放", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "日K", exact: true }).click();
  const panel = page.locator('.shared-kline-host .msd-kline');
  const svg = panel.locator('.msd-candle-chart');
  await svg.dispatchEvent('wheel', { deltaY: -80, bubbles: true, cancelable: true });
  await expect(panel).toHaveAttribute('data-capacity', '48');
  await svg.dispatchEvent('wheel', { deltaY: -80, shiftKey: true, bubbles: true, cancelable: true });
  await expect(panel).toHaveAttribute('data-offset', '12');
  await svg.click({ position: { x: 100, y: 80 } });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  const xs = await panel.locator('.kline-crosshair').evaluateAll(nodes => nodes.map(node => node.getAttribute('x1')));
  expect(new Set(xs).size).toBe(1);
  await panel.getByRole('button', {name:'关闭K线详细信息'}).click();
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: 100, clientY: 100 }, { identifier: 2, clientX: 200, clientY: 100 }], bubbles: true, cancelable: true });
  await svg.dispatchEvent('touchmove', { touches: [{ identifier: 1, clientX: 90, clientY: 100 }, { identifier: 2, clientX: 220, clientY: 100 }], bubbles: true, cancelable: true });
  await expect(panel).toHaveAttribute('data-capacity', '30');
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  const rect = await svg.boundingBox();
  if (!rect) throw new Error('K线绘图区不可见');
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: rect.x + 50, clientY: rect.y + 50 }], bubbles: true });
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  await svg.dispatchEvent('click', { clientX: rect.x + 50, bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: rect.x + 50, clientY: rect.y + 50 }], bubbles: true });
  await svg.dispatchEvent('touchmove', { touches: [{ identifier: 1, clientX: rect.x + 90, clientY: rect.y + 50 }], bubbles: true, cancelable: true });
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: rect.x + 50, clientY: rect.y + 50 }], bubbles: true });
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(0);
});

test("详情点击显示，移动吸附更新，关闭后不再跟随，轮廓拉伸不变粗", async ({ page }) => {
 await page.setViewportSize({ width: 1020, height: 833 });
 await page.goto("/?tradingE2E=1");
 await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
 await page.getByRole("button", { name: "日K", exact: true }).click();
 const panel = page.locator('.shared-kline-host .msd-kline');
 const svg = panel.locator('.msd-candle-chart');
 await expect(panel.locator('.kline-crosshair')).toHaveCount(0);
 await svg.click({ position: { x: 100, y: 60 } });
 await expect(panel.getByRole('complementary', { name: 'K线详细信息' })).toBeVisible();
 const oldX = await panel.locator('.kline-crosshair').first().getAttribute('x1');
 const box = await svg.boundingBox(); if (!box) throw new Error('图表不可见');
 await page.mouse.move(box.x + box.width - 30, box.y + 80);
 await expect(panel.locator('.kline-crosshair').first()).not.toHaveAttribute('x1', oldX!);
 await svg.click({ position: { x: 100, y: 60 } });
 await expect(panel.getByRole('complementary', { name: 'K线详细信息' })).toHaveCount(0);
 await page.mouse.move(box.x + 60, box.y + 80);
 await expect(panel.locator('.kline-crosshair')).toHaveCount(0);
 const styles = await panel.locator('.msd-candle-chart g rect').first().evaluate(el => ({ effect: el.ownerDocument.defaultView!.getComputedStyle(el).vectorEffect, width: el.ownerDocument.defaultView!.getComputedStyle(el).strokeWidth }));
 expect(styles).toEqual({ effect: 'non-scaling-stroke', width: '1px' });
 await page.setViewportSize({width:1440,height:900});
 await expect(panel.locator('.msd-candle-chart g rect').first()).toHaveCSS('stroke-width', '1px');
});
