import { expect, test } from "@playwright/test";

test.setTimeout(10_000);

test("窄窗口看盘交易的周月K说明不裁切底部指标按钮", async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 740 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "买入此股票", exact: true }).click();
  for (const period of ["周K", "月K"]) {
    await page.getByRole("tab", { name: period, exact: true }).click();
    const chart = page.locator(".shared-kline-host .msd-kline");
    const controls = chart.locator(".shared-indicator-controls");
    const bounds = await chart.boundingBox();
    const buttons = await controls.boundingBox();
    expect(bounds).not.toBeNull();
    expect(buttons).not.toBeNull();
    expect(buttons!.y + buttons!.height).toBeLessThanOrEqual(bounds!.y + bounds!.height + 1);
    await controls.getByRole("button", { name: "MACD", exact: true }).click();
    await expect(controls.getByRole("button", { name: "MACD", exact: true })).toHaveAttribute("aria-pressed", "true");
    await expect(page.locator(".desktop-account-bar")).toBeInViewport();
  }
});

test("图表隐藏后撤下显示菜单，返回看盘不会遗留弹层", async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  await page.getByRole("button", { name: "图表显示设置", exact: true }).click();
  await page.getByRole("menuitem", { name: "均线", exact: true }).press("F10");
  await expect(page.locator("#section-company")).toBeVisible();
  await expect(page.getByRole("menu")).toHaveCount(0);
  await page.getByRole("button", { name: "走势图", exact: true }).click();
  await expect(page.getByRole("menu")).toHaveCount(0);
  await expect(page.getByRole("button", { name: "图表显示设置", exact: true })).toHaveAttribute("aria-expanded", "false");
});

test("320px 手机显示菜单保持边界，多选后切周期保留设置且点击外部关闭", async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 844 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("button", { name: /稳健实业 600101/ }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  await page.getByRole("button", { name: "图表显示设置", exact: true }).click();
  await page.getByRole("menuitem", { name: "均线", exact: true }).click();
  await page.getByRole("menuitemcheckbox", { name: "MA20", exact: true }).click();
  const bounds = await page.getByRole("menu").boundingBox();
  expect(bounds).not.toBeNull();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320);
  expect(bounds!.y).toBeGreaterThanOrEqual(0);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844);
  await page.getByRole("tab", { name: "周K", exact: true }).click();
  await expect(page.getByRole("menu")).toHaveCount(0);
  await expect(page.getByRole("button", { name: /^MA20：/ })).toHaveAttribute("aria-pressed", "false");
  await page.getByRole("tab", { name: "分时", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  await expect(page.getByRole("button", { name: /^MA20：/ })).toHaveAttribute("aria-pressed", "false");
  expect(await page.locator("html").evaluate(el => el.scrollWidth > el.clientWidth)).toBe(false);
});

test("桌面与手机共用周期选择，日周月入口和均线设置保持一致", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  const tabs = page.getByRole("tablist", { name: "图表周期" });
  await expect(tabs.getByRole("tab", { name: "周K", exact: true })).toHaveCount(1);
  await tabs.getByRole("tab", { name: "日K", exact: true }).click();
  const chart = page.locator(".shared-kline-host .msd-kline");
  const dailyCount = Number(await chart.getAttribute("data-kline-count"));
  await chart.getByRole("button", { name: /^MA5：/ }).click();
  await tabs.getByRole("tab", { name: "日K", exact: true }).press("ArrowRight");
  await expect(tabs.getByRole("tab", { name: "周K", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(chart).toHaveAttribute("data-kline-count", String(Math.ceil(dailyCount / 5)));
  await expect(chart.getByRole("button", { name: /^MA5：/ })).toHaveAttribute("aria-pressed", "false");
  await expect(chart).toContainText("每5个游戏交易日合并");
  await tabs.getByRole("tab", { name: "月K", exact: true }).click();
  await expect(chart).toHaveAttribute("data-kline-count", String(Math.ceil(dailyCount / 20)));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("button", { name: /稳健实业 600101/ }).click();
  await expect(page.getByRole("tab", { name: "月K", exact: true })).toHaveAttribute("aria-selected", "true");
  await page.setViewportSize({ width: 1020, height: 833 });
  await expect(tabs.getByRole("tab", { name: "月K", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page).toHaveTitle("股票模拟游戏");
});

test("显示菜单分层选择均线和副图，Escape逐层返回且不影响直接按钮", async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  const chart = page.locator(".shared-kline-host .msd-kline");
  await expect(chart.getByRole("button", { name: "图表显示设置", exact: true })).toHaveCount(1);
  await chart.getByRole("button", { name: "图表显示设置", exact: true }).click();
  await page.getByRole("menuitem", { name: "均线", exact: true }).press("ArrowRight");
  await page.getByRole("menuitemcheckbox", { name: "MA5", exact: true }).click();
  await expect(chart.getByRole("button", { name: /^MA5：/ })).toHaveAttribute("aria-pressed", "false");
  await page.getByRole("menuitemcheckbox", { name: "MA5", exact: true }).press("Escape");
  await expect(page.getByRole("menuitem", { name: "均线", exact: true })).toBeFocused();
  await page.getByRole("menuitem", { name: "副图指标", exact: true }).click();
  await page.getByRole("menuitemradio", { name: "MACD", exact: true }).click();
  await expect(chart.getByRole("button", { name: "MACD", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("menu")).toHaveCount(0);
  await expect(chart.getByRole("button", { name: "图表显示设置", exact: true })).toBeFocused();
});

test("个股右栏在盘口、成交明细和行情摘要间切换，键盘与切股保持一致", async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  const tabs = page.getByRole("tablist", { name: "个股行情信息" });
  await tabs.getByRole("tab", { name: "盘口", exact: true }).press("ArrowRight");
  await expect(tabs.getByRole("tab", { name: "明细", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(page.getByRole("table", { name: "600101 最近逐笔成交，数量单位为手" })).toBeVisible();
  await expect(page.getByText("暂无该股票的成交缓存", { exact: true })).toBeVisible();
  await tabs.getByRole("tab", { name: "明细", exact: true }).press("End");
  await expect(tabs.getByRole("tab", { name: "行情", exact: true })).toBeFocused();
  await tabs.getByRole("tab", { name: "行情", exact: true }).press("Tab");
  await expect(page.getByRole("tabpanel", { name: "行情", exact: true })).toBeFocused();
  await expect(page.getByRole("region", { name: "当日行情摘要" })).toContainText("尚无成交，开盘价及高低价未形成");
  await page.getByRole("navigation", { name: "个股列表" }).getByRole("button", { name: /芯片科技/ }).click();
  await tabs.getByRole("tab", { name: "明细", exact: true }).click();
  await expect(page.getByRole("table", { name: "002156 最近逐笔成交，数量单位为手" })).toBeVisible();
  await tabs.getByRole("tab", { name: "盘口", exact: true }).click();
  await expect(page.getByRole("complementary", { name: "五档盘口，数量单位为手" })).toBeVisible();
  await expect(page.locator(".desktop-account-bar")).toBeInViewport();
});

test("行情单击预览、双击进入个股，F10 与返回保持选择和图表周期", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  await expect(page.locator('.desktop-terminal[data-view="quotes"]')).toBeVisible();
  const row = page.locator('.ag-row[row-id="002156"]');
  await row.click();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await expect(page.locator('.desktop-terminal[data-view="quotes"]')).toBeVisible();
  await row.dblclick();
  await expect(page.locator('.desktop-terminal[data-view="stock"]')).toBeVisible();
  await expect(page.getByRole("navigation", { name: "个股列表" })).toBeVisible();
  await page.locator("#section-trade").getByRole("tab", { name: "日K", exact: true }).click();
  await page.locator("#section-trade").getByRole("button", { name: "无", exact: true }).click();
  await page.getByRole("button", { name: "公司资料 F10", exact: true }).click();
  await expect(page.locator("#section-company")).toBeVisible();
  await expect(page.locator("#section-trade")).toBeHidden();
  await page.getByRole("button", { name: "走势图", exact: true }).click();
  await expect(page.locator(".chart-tab.active")).toHaveText("日K");
  await expect(page.locator("#section-trade").getByRole("button", { name: "无", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "返回行情", exact: true }).click();
  await expect(page.locator('.desktop-terminal[data-view="quotes"]')).toBeVisible();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await expect(page.getByRole("contentinfo", { name: "模拟账户摘要" })).toBeInViewport();
});

test("交易和游戏管理各有入口，切换不丢委托草稿，横竖屏使用不同导航", async ({ page }) => {
  await page.setViewportSize({ width: 844, height: 390 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  const quantity = page.getByPlaceholder("买入按手；零股一次卖完");
  await quantity.fill("300");
  await nav.getByRole("button", { name: "游戏", exact: true }).click();
  await expect(page.getByRole("button", { name: "日终存档说明" })).toBeVisible();
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  await expect(quantity).toHaveValue("300");
  await expect(page.locator("#section-positions")).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("navigation", { name: "主导航" })).toBeVisible();
  await expect(nav).toHaveCount(0);
  await expect(page.locator(".desktop-account-bar")).toHaveCount(0);
});

test("当前个股交易入口纠正另一证券草稿，F10 与公司页始终跟随个股", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  const code = page.locator('#section-order').getByLabel('股票', {exact:true});
  await code.selectOption("002156");
  await page.getByPlaceholder("买入按手；零股一次卖完").fill("300");
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await page.getByRole("navigation", { name: "个股列表" }).getByRole("button", { name: /稳健实业/ }).click();
  await page.getByRole("button", { name: "交易此股票", exact: true }).click();
  await expect(code).toHaveValue("600101");
  await expect(page.getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("300");
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await page.keyboard.press("F10");
  await expect(page.getByRole("region", {name:"公司信息"})).toHaveAttribute("data-company-id", "C-600101");
  await page.getByRole("navigation", {name:"个股列表"}).getByRole("button", {name:/芯片科技/}).click();
  await expect(page.getByRole("region", {name:"公司信息"})).toHaveAttribute("data-company-id", "C-002156");
});

test("1020窗口个股图保留完整时间轴，价量左右边界一致且盘口不溢出", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  const chart = page.locator(".desktop-intraday");
  await expect(chart).toBeVisible();
  await expect(chart.getByText("11:30/13:00", { exact: true })).toBeVisible();
  const price = await page.locator(".intraday-price-plot").boundingBox();
  const volume = await page.locator(".intraday-volume-plot").boundingBox();
  expect(price).not.toBeNull();
  expect(volume).not.toBeNull();
  expect(Math.abs(price!.x - volume!.x)).toBeLessThan(1);
  expect(Math.abs(price!.width - volume!.width)).toBeLessThan(1);
  expect(price!.width).toBeGreaterThan(380);
  await expect(page.locator(".order-book")).toBeInViewport();
  await expect(page.getByRole("contentinfo", { name: "模拟账户摘要" })).toBeInViewport();
  const overflow = await page.locator(".terminal-body").evaluate(el => el.scrollWidth > el.clientWidth);
  expect(overflow).toBe(false);
  await page.locator("#section-trade").getByRole("tab", { name: "日K", exact: true }).click();
  await expect(chart).toHaveCount(1);
  await expect(chart).toBeHidden();
  await page.locator("#section-trade").getByRole("tab", { name: "分时", exact: true }).click();
  await expect(chart).toBeVisible();
});

test("均线按钮可多选，关闭其中一条不影响其他均线", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  const group = page.getByRole("group", { name: "均线（可多选）" });
  const ma20 = group.getByRole("button", { name: /^MA20：/ });
  const ma60 = group.getByRole("button", { name: /^MA60：/ });
  await expect(group.getByRole("button", { name: /^MA\d+：/ })).toHaveCount(5);
  await expect(group.getByRole("button", { name: "图表显示设置", exact: true })).toHaveCount(1);
  await expect(ma20).toHaveAttribute("aria-pressed", "true");
  await expect(ma60).toHaveAttribute("aria-pressed", "true");
  await ma20.click();
  await expect(ma20).toHaveAttribute("aria-pressed", "false");
  await expect(ma60).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("tab", { name: "分时", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  await expect(ma60).toHaveAttribute("aria-pressed", "true");
  await expect(ma20).toHaveAttribute("aria-pressed", "false");
});

test("共用K线支持滚轮、Shift平移、点击对齐和双指缩放", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  const panel = page.locator('.shared-kline-host .msd-kline');
  const svg = panel.locator('.msd-candle-chart');
  await svg.dispatchEvent('wheel', { deltaY: -80, bubbles: true, cancelable: true });
  await expect(panel).toHaveAttribute('data-capacity', '48');
  await svg.dispatchEvent('wheel', { deltaY: -80, shiftKey: true, bubbles: true, cancelable: true });
  await expect(panel).toHaveAttribute('data-offset', '12');
  await svg.click({ position: { x: 100, y: 80 } });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  const xs = await panel.locator('.kline-crosshair').evaluateAll(nodes => nodes.map(node => node.getAttribute('x1')));
  expect(new Set(xs).size).toBe(1);
  await panel.getByRole('button', {name:'关闭K线详细信息'}).click();
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: 100, clientY: 100 }, { identifier: 2, clientX: 200, clientY: 100 }], bubbles: true, cancelable: true });
  await svg.dispatchEvent('touchmove', { touches: [{ identifier: 1, clientX: 90, clientY: 100 }, { identifier: 2, clientX: 220, clientY: 100 }], bubbles: true, cancelable: true });
  await expect(panel).toHaveAttribute('data-capacity', '30');
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  const rect = await svg.boundingBox();
  if (!rect) throw new Error('K线绘图区不可见');
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: rect.x + 50, clientY: rect.y + 50 }], bubbles: true });
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  await svg.dispatchEvent('click', { clientX: rect.x + 50, bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: rect.x + 50, clientY: rect.y + 50 }], bubbles: true });
  await svg.dispatchEvent('touchmove', { touches: [{ identifier: 1, clientX: rect.x + 90, clientY: rect.y + 50 }], bubbles: true, cancelable: true });
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(3);
  await svg.dispatchEvent('touchstart', { touches: [{ identifier: 1, clientX: rect.x + 50, clientY: rect.y + 50 }], bubbles: true });
  await svg.dispatchEvent('touchend', { touches: [], bubbles: true });
  await expect(panel.locator('.kline-crosshair')).toHaveCount(0);
});

test("详情点击显示，移动吸附更新，关闭后不再跟随，轮廓拉伸不变粗", async ({ page }) => {
 await page.setViewportSize({ width: 1020, height: 833 });
 await page.goto("/?tradingE2E=1");
 await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
 await page.getByRole("tab", { name: "日K", exact: true }).click();
 const panel = page.locator('.shared-kline-host .msd-kline');
 const svg = panel.locator('.msd-candle-chart');
 await expect(panel.locator('.kline-crosshair')).toHaveCount(0);
 await svg.click({ position: { x: 100, y: 60 } });
 await expect(panel.getByRole('complementary', { name: 'K线详细信息' })).toBeVisible();
 const oldX = await panel.locator('.kline-crosshair').first().getAttribute('x1');
 const box = await svg.boundingBox(); if (!box) throw new Error('图表不可见');
 await page.mouse.move(box.x + box.width - 30, box.y + 80);
 await expect(panel.locator('.kline-crosshair').first()).not.toHaveAttribute('x1', oldX!);
 await svg.click({ position: { x: 100, y: 60 } });
 await expect(panel.getByRole('complementary', { name: 'K线详细信息' })).toHaveCount(0);
 await page.mouse.move(box.x + 60, box.y + 80);
 await expect(panel.locator('.kline-crosshair')).toHaveCount(0);
 const styles = await panel.locator('.msd-candle-chart g rect').first().evaluate(el => ({ effect: el.ownerDocument.defaultView!.getComputedStyle(el).vectorEffect, width: el.ownerDocument.defaultView!.getComputedStyle(el).strokeWidth }));
 expect(styles).toEqual({ effect: 'non-scaling-stroke', width: '1px' });
 await page.setViewportSize({width:1440,height:900});
 await expect(panel.locator('.msd-candle-chart g rect').first()).toHaveCSS('stroke-width', '1px');
});

test("盘口买卖展开底部交易栏，保留看盘与草稿，Escape收起并恢复入口焦点", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  const entry = page.getByRole("button", { name: "买入此股票", exact: true });
  await entry.click();
  const dock = page.getByRole("region", { name: "看盘交易栏" });
  await expect(dock).toBeVisible();
  await expect(page.locator("#section-trade")).toBeVisible();
  await expect(page.locator(".msd-candle-chart")).toBeVisible();
  const order = page.locator("#section-order");
  await order.getByPlaceholder("委托价").fill("10.75");
  await order.getByPlaceholder("买入按手；零股一次卖完").fill("300");
  await page.getByRole("button", { name: "卖出此股票", exact: true }).click();
  await expect(order).toHaveAttribute("data-trade-side", "Sell");
  await expect(order.getByPlaceholder("委托价")).toHaveValue("10.75");
  await expect(order.getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("300");
  const bounds = await dock.boundingBox();
  const chart = await page.locator("#section-trade").boundingBox();
  if (!bounds || !chart) throw new Error("看盘交易栏或图表不可见");
  expect(bounds.y).toBeGreaterThanOrEqual(chart.y + chart.height - 1);
  await page.keyboard.press("Escape");
  await expect(dock).toBeHidden();
  await expect(page.getByRole("button", { name: "卖出此股票", exact: true })).toBeFocused();
  await entry.click();
  await expect(order.getByPlaceholder("委托价")).toHaveValue("10.75");
  await expect(order.getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("300");
  await page.getByRole("button", { name: "资金持仓", exact: true }).click();
  await expect(page.locator("#section-positions")).toBeVisible();
  await expect(page.locator("#section-order")).toBeVisible();
  expect(await page.locator("#section-order").count()).toBe(1);
});

test("看盘交易栏在1020横屏和竖屏切换时复用同一份委托草稿", async ({ page }) => {
  await page.setViewportSize({ width: 1020, height: 833 });
  await page.goto("/?tradingE2E=1");
  await page.getByRole("navigation", { name: "桌面主导航" }).getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "买入此股票", exact: true }).click();
  await page.locator("#section-order").getByPlaceholder("买入按手；零股一次卖完").fill("500");
  await expect(page.locator("#section-trade")).toBeVisible();
  expect(await page.locator(".app-root").evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true);
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole("navigation", { name: "主导航" }).getByRole("button", { name: "交易", exact: true }).click();
  await expect(page.locator("#section-order").getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("500");
  await page.getByRole("button", { name: "关闭交易面板", exact: true }).click({ position: { x: 10, y: 10 } });
  await page.setViewportSize({ width: 1020, height: 833 });
  await expect(page.locator("#section-order").getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("500");
});

test("当前窗口看盘下单的按钮和K线指标无需滚动，完整交易页两个面板从同一行开始", async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 833 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("tab", { name: "日K", exact: true }).click();
  await page.getByRole("button", { name: "买入此股票", exact: true }).click();
  const order = page.locator("#section-order");
  const buy = await order.getByRole("button", { name: "买入", exact: true }).boundingBox();
  const panel = await order.boundingBox();
  const indicator = await page.locator(".msd-kdj").boundingBox();
  const controls = await page.locator(".shared-kline-host .shared-indicator-controls").boundingBox();
  const chart = await page.locator("#section-trade").boundingBox();
  if (!buy || !panel || !indicator || !chart || !controls) throw new Error("看盘下单区域不可见");
  expect(buy.y + buy.height).toBeLessThanOrEqual(panel.y + panel.height);
  expect(indicator.y + indicator.height).toBeLessThanOrEqual(chart.y + chart.height);
  expect(controls.y + controls.height).toBeLessThanOrEqual(chart.y + chart.height);
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  const left = await page.locator(".terminal-slot-section-order").boundingBox();
  const right = await page.locator(".terminal-slot-section-positions").boundingBox();
  if (!left || !right) throw new Error("交易页面板不可见");
  expect(Math.abs(left.y - right.y)).toBeLessThan(1);
});

test("同屏委托切换证券同步图表，重复选择不覆盖草稿，隐藏底栏不接管Escape", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "买入此股票", exact: true }).click();
  const order = page.locator("#section-order");
  await order.getByLabel("股票", { exact: true }).selectOption("002156");
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await order.getByPlaceholder("委托价").fill("27.50");
  await page.getByRole("navigation", { name: "个股列表" }).getByRole("button", { name: /芯片科技/ }).click();
  await expect(order.getByPlaceholder("委托价")).toHaveValue("27.50");
  await nav.getByRole("button", { name: "游戏", exact: true }).click();
  const save = page.getByRole("button", { name: "日终存档说明" });
  await save.focus();
  await page.keyboard.press("Escape");
  await expect(save).toBeFocused();
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await expect(page.getByRole("region", { name: "看盘交易栏" })).toBeVisible();
  await expect(order.getByPlaceholder("委托价")).toHaveValue("27.50");
});

test("完整交易页切股后返回看盘，行情与委托标的一致且保持草稿", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto("/?tradingE2E=1");
  const nav = page.getByRole("navigation", { name: "桌面主导航" });
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await page.getByRole("button", { name: "买入此股票", exact: true }).click();
  await nav.getByRole("button", { name: "交易", exact: true }).click();
  const order = page.locator("#section-order");
  await order.getByLabel("股票", { exact: true }).selectOption("002156");
  await order.getByPlaceholder("委托价").fill("27.50");
  await order.getByPlaceholder("买入按手；零股一次卖完").fill("300");
  await nav.getByRole("button", { name: "个股", exact: true }).click();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await expect(order.getByLabel("股票", { exact: true })).toHaveValue("002156");
  await expect(order.getByPlaceholder("委托价")).toHaveValue("27.50");
  await expect(order.getByPlaceholder("买入按手；零股一次卖完")).toHaveValue("300");
  await nav.getByRole("button", { name: "行情", exact: true }).click();
  await expect(page.locator(".stock-detail-header")).toContainText("002156");
  await expect(order.getByPlaceholder("委托价")).toHaveValue("27.50");
});

test("移动详情从委托切股后标题和详情证券保持一致", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/?tradingE2E=1");
  await page.locator(".mobile-market-row").first().click();
  await expect(page).toHaveTitle("稳健实业 — 股票模拟游戏");
  await page.getByRole("navigation", { name: "主导航" }).getByRole("button", { name: "交易", exact: true }).click();
  await page.locator("#section-order").getByLabel("股票", { exact: true }).selectOption("002156");
  await expect(page).toHaveTitle("芯片科技 — 股票模拟游戏");
  await page.keyboard.press("Escape");
  await expect(page.locator(".msd-security-title")).toContainText("芯片科技");
  await expect(page.locator(".msd-security-title")).toContainText("002156");
});
