import { exact, integer, map, nullable, record } from "../primitives.ts"
import { accountKey, marketMinute, money, stockKey, type StringMap } from "./common.ts"

export type PersonalWatchlist = { readonly stocks: StringMap<WatchedStock>; readonly latest_attention_minute: string }
export type WatchedStock = { readonly last_observed_market_minute: string }
export type PersonalPriceMemory = { readonly stocks: StringMap<StockPriceMemory> }
export type StockPriceMemory = { readonly first_observed_minute: string; readonly first_observed_price: number; readonly last_observed_minute: string; readonly last_observed_price: number; readonly observed_high: number; readonly observed_low: number; readonly last_public_history_read_minute: string | null; readonly public_history_read_count: number; readonly last_touched_minute: string }

export function parseWatchlists(value: unknown, path = "watchlists"): StringMap<PersonalWatchlist> { return map(value, path, accountKey, parseWatchlist) }
export function parsePriceMemories(value: unknown, path = "price_memories"): StringMap<PersonalPriceMemory> { return map(value, path, accountKey, parsePriceMemory) }

function parseWatchlist(value: unknown, path: string): PersonalWatchlist { const parsed = record(value, path); exact(parsed, ["stocks", "latest_attention_minute"], path); return { stocks: map(parsed.stocks, `${path}.stocks`, stockKey, parseWatchedStock), latest_attention_minute: marketMinute(parsed.latest_attention_minute, `${path}.latest_attention_minute`) } }
function parseWatchedStock(value: unknown, path: string): WatchedStock { const parsed = record(value, path); exact(parsed, ["last_observed_market_minute"], path); return { last_observed_market_minute: marketMinute(parsed.last_observed_market_minute, `${path}.last_observed_market_minute`) } }
function parsePriceMemory(value: unknown, path: string): PersonalPriceMemory { const parsed = record(value, path); exact(parsed, ["stocks"], path); return { stocks: map(parsed.stocks, `${path}.stocks`, stockKey, parseStockPriceMemory) } }
function parseStockPriceMemory(value: unknown, path: string): StockPriceMemory { const parsed = record(value, path); exact(parsed, ["first_observed_minute", "first_observed_price", "last_observed_minute", "last_observed_price", "observed_high", "observed_low", "last_public_history_read_minute", "public_history_read_count", "last_touched_minute"], path); return { first_observed_minute: marketMinute(parsed.first_observed_minute, `${path}.first_observed_minute`), first_observed_price: money(parsed.first_observed_price, `${path}.first_observed_price`), last_observed_minute: marketMinute(parsed.last_observed_minute, `${path}.last_observed_minute`), last_observed_price: money(parsed.last_observed_price, `${path}.last_observed_price`), observed_high: money(parsed.observed_high, `${path}.observed_high`), observed_low: money(parsed.observed_low, `${path}.observed_low`), last_public_history_read_minute: nullable(parsed.last_public_history_read_minute, `${path}.last_public_history_read_minute`, marketMinute), public_history_read_count: integer(parsed.public_history_read_count, `${path}.public_history_read_count`, 0), last_touched_minute: marketMinute(parsed.last_touched_minute, `${path}.last_touched_minute`) } }
