import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import test from "node:test"
import type { ReportFrequency } from "../../types/generated/ReportFrequency"
import type { MonthlyReportSchedule } from "../../types/generated/MonthlyReportSchedule"
import type { MonthlyReportDelay } from "../../types/generated/MonthlyReportDelay"
import type { MonthlyReportPreset } from "../../types/generated/MonthlyReportPreset"
import { parseReportFrequency } from "./report-frequency.ts"

test("实际Rust生成bindings完整包含Monthly排期而非手工旧Monthly字符串", { timeout: 10000 }, () => {
  const preset: MonthlyReportPreset = "FirstDayEvening"
  const delay: MonthlyReportDelay = { Uniform: { max_days: 2 } }
  const schedule: MonthlyReportSchedule = { Preset: { preset, delay } }
  const frequency: ReportFrequency = { Monthly: { schedule } }
  assert.deepEqual(parseReportFrequency(frequency), frequency)
  for (const [file, pattern] of [
    ["ReportFrequency", /"Monthly"\s*:\s*\{\s*schedule:\s*MonthlyReportSchedule/],
    ["MonthlyReportSchedule", /"Custom"\s*:\s*\{[^}]*day:\s*number[^}]*second_of_day:\s*number/],
    ["MonthlyReportDelay", /"Uniform"\s*:\s*\{\s*max_days:\s*number/],
    ["MonthlyReportPreset", /"FirstDayEvening"\s*\|\s*"TenthDayEvening"/],
  ] as const) {
    const content = readFileSync(new URL(`../../types/generated/${file}.ts`, import.meta.url), "utf8")
    assert.match(content, /generated by \[ts-rs\]/)
    assert.match(content, pattern)
  }
})
